# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
import numpy as np
print(np.__version__)

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
np.random.rand(3, 2)

array([[0.7710105 , 0.23330414],
       [0.37759993, 0.28950282],
       [0.51339794, 0.5332065 ]])

In [9]:
np.random.randn(3, 2)

array([[-0.72364533,  0.98697949],
       [ 0.43025384,  0.14022007],
       [-0.16253638, -0.31446157]])

In [11]:
np.random.randint(0, 10, size=(3, 2))

array([[7, 1],
       [0, 3],
       [3, 8]])

#### 4. Print *a*.


In [20]:
a= np.random.rand(3, 2)
print(a)

[[0.62957977 0.16874548]
 [0.40335655 0.16130971]
 [0.03674067 0.10581922]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [22]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [25]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
a= np.random.rand(3, 2)
b = np.ones((5, 2, 3))
print(a.size == b.size) 

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
No because de vector do not have the same size

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [30]:
a= np.random.rand(2, 3,5)
c = np.transpose(b, (1, 2, 0))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [33]:
d = a + c
print(d)

[[[1.15657837 1.66157313 1.90585511 1.55729028 1.68528078]
  [1.54217501 1.68376847 1.33261482 1.45314881 1.02946348]
  [1.42287962 1.31126538 1.77528486 1.37708212 1.47762633]]

 [[1.25515175 1.8897084  1.21114273 1.43532507 1.43861866]
  [1.80239005 1.08887557 1.55372881 1.76260528 1.99937611]
  [1.13438457 1.7015668  1.89508288 1.40682671 1.72024678]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [35]:
print("Array a:")
print(a)

print("\nArray d (a + c):")
print(d)
 #Every element in d is exactly 1 more than the corresponding element in a

Array a:
[[[0.15657837 0.66157313 0.90585511 0.55729028 0.68528078]
  [0.54217501 0.68376847 0.33261482 0.45314881 0.02946348]
  [0.42287962 0.31126538 0.77528486 0.37708212 0.47762633]]

 [[0.25515175 0.8897084  0.21114273 0.43532507 0.43861866]
  [0.80239005 0.08887557 0.55372881 0.76260528 0.99937611]
  [0.13438457 0.7015668  0.89508288 0.40682671 0.72024678]]]

Array d (a + c):
[[[1.15657837 1.66157313 1.90585511 1.55729028 1.68528078]
  [1.54217501 1.68376847 1.33261482 1.45314881 1.02946348]
  [1.42287962 1.31126538 1.77528486 1.37708212 1.47762633]]

 [[1.25515175 1.8897084  1.21114273 1.43532507 1.43861866]
  [1.80239005 1.08887557 1.55372881 1.76260528 1.99937611]
  [1.13438457 1.7015668  1.89508288 1.40682671 1.72024678]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [37]:
e = a * c
print(e)

[[[0.15657837 0.66157313 0.90585511 0.55729028 0.68528078]
  [0.54217501 0.68376847 0.33261482 0.45314881 0.02946348]
  [0.42287962 0.31126538 0.77528486 0.37708212 0.47762633]]

 [[0.25515175 0.8897084  0.21114273 0.43532507 0.43861866]
  [0.80239005 0.08887557 0.55372881 0.76260528 0.99937611]
  [0.13438457 0.7015668  0.89508288 0.40682671 0.72024678]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# yess because multiplying by an array of ones doesn’t change the original values in a.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [39]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 1.9993761069929663
Min value in d: 1.029463478396011
Mean value in d: 1.522230557687829


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
f = np.empty(d.shape)
print(f)

[[[0.15657837 0.66157313 0.90585511 0.55729028 0.68528078]
  [0.54217501 0.68376847 0.33261482 0.45314881 0.02946348]
  [0.42287962 0.31126538 0.77528486 0.37708212 0.47762633]]

 [[0.25515175 0.8897084  0.21114273 0.43532507 0.43861866]
  [0.80239005 0.08887557 0.55372881 0.76260528 0.99937611]
  [0.13438457 0.7015668  0.89508288 0.40682671 0.72024678]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [43]:

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

print(f)

[[[ 25.  75.  75.  75.  75.]
  [ 75.  75.  25.  25.   0.]
  [ 25.  25.  75.  25.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  75. 100.]
  [ 25.  75.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [45]:

print(d)

print(f)

[[[1.15657837 1.66157313 1.90585511 1.55729028 1.68528078]
  [1.54217501 1.68376847 1.33261482 1.45314881 1.02946348]
  [1.42287962 1.31126538 1.77528486 1.37708212 1.47762633]]

 [[1.25515175 1.8897084  1.21114273 1.43532507 1.43861866]
  [1.80239005 1.08887557 1.55372881 1.76260528 1.99937611]
  [1.13438457 1.7015668  1.89508288 1.40682671 1.72024678]]]
[[[ 25.  75.  75.  75.  75.]
  [ 75.  75.  25.  25.   0.]
  [ 25.  25.  75.  25.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  75. 100.]
  [ 25.  75.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [47]:

f_str = np.empty(d.shape, dtype=object)

# Loop through and assign labels
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f_str[i, j, k] = 'A'
            elif value == d_max:
                f_str[i, j, k] = 'E'
            elif value == d_mean:
                f_str[i, j, k] = 'C'
            elif d_min < value < d_mean:
                f_str[i, j, k] = 'B'
            elif d_mean < value < d_max:
                f_str[i, j, k] = 'D'


print("Array d (values):")
print(d)

print("\nArray f_str (labels):")
print(f_str)


Array d (values):
[[[1.15657837 1.66157313 1.90585511 1.55729028 1.68528078]
  [1.54217501 1.68376847 1.33261482 1.45314881 1.02946348]
  [1.42287962 1.31126538 1.77528486 1.37708212 1.47762633]]

 [[1.25515175 1.8897084  1.21114273 1.43532507 1.43861866]
  [1.80239005 1.08887557 1.55372881 1.76260528 1.99937611]
  [1.13438457 1.7015668  1.89508288 1.40682671 1.72024678]]]

Array f_str (labels):
[[['B' 'D' 'D' 'D' 'D']
  ['D' 'D' 'B' 'B' 'A']
  ['B' 'B' 'D' 'B' 'B']]

 [['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'E']
  ['B' 'D' 'D' 'B' 'D']]]
